### ISSUE TITLE
clasp error code

### ISSUE THREAD

**Issue by Aluriak** [potassco/clasp#10]
As indicated in last lines of the [readme](https://github.com/potassco/clasp#usage): 

  In addition to printing status information, clasp also
  provides information about the computation via its exit status.
  The exit status is:
    
    10 : if the problem was found to be satisfiable
    20 : if the problem was proved to be unsatisfiable
    0  : if the satisfiability of problem is not known,
         because search was either interrupted or not started
    127: if clasp ran out of memory

I found that at least one other code is used, 11, if problem was found to be satisfiable but interrupted by the time limit.

Is there any comprehensive list of all error code used by clasp and their meaning ? (unless this list was just missing the 11 ?)
Or maybe somewhere in the source code where all cases are implemented ?

I also note that, when time limit is given, if no solution is found during the time limit the output value is 1, which i found unexpected.

**Comment by BenKaufmann** [comment]
Hi,
clasp exit codes more or less follow  Section 3 of this proposal:
https://www.mat.unical.it/aspcomp2013/files/aspoutput.txt
With the exception that clasp does not use the "ALLOPT"-flag to distinguish between "some optimal models found" and "all optimal models found" when *enumerating* optimal models ('opt-mode=optN').
That is, in this mode clasp returns 30 only after *all* optimal models were found. 

The set of exit codes is specified in app/clasp_app.h:
https://github.com/potassco/clasp/blob/master/app/clasp_app.h#L44

As you can see, clasp uses bit 5 for signaling an out of memory error.
