### ISSUE TITLE
assertion failure in Clasp::Asp::LogicProgram::finalizeDisjunctions

### ISSUE THREAD

**Issue by tkren** [potassco/clasp#13]
The following program breaks clasp 3.3.2 (and clingo 5.2.1):
 
     a|b:-not c.
     c|d:-not a.

Observe:

    $ gringo <<EOF | clasp
    a|b:-not c.
    c|d:-not a.
    EOF
    clasp version 3.3.2
    Reading from stdin
    *** ERROR: (clasp): void Clasp::Asp::LogicProgram::finalizeDisjunctions(Clasp::Asp::Preprocessor&, Clasp::uint32)@1280: assertion failure: check('dx == bot || getRootAtom(supportLit.var())->var() == dx.var()') failed
    UNKNOWN
    
    Models       : 0+
    Calls        : 1
    Time         : 0.000s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
    CPU Time     : 0.000s
    $ echo $?               
    65

**Comment by BenKaufmann** [comment]
Hi Thomas,
thank you for the report.
Fixed in dev.

**Comment by tkren** [comment]
works as expected, cherry-picked into clasp 3.3.2-4 and gringo 5.2.1-3
