### ISSUE TITLE
Questions on lemmas

### ISSUE THREAD

**Issue by capiman** [potassco/clasp#17]
Hello,
I am very new to clasp, therefore excuse if my questions are stupid.
I tried to call clasp 3.3.3 with some of the lemma options, mainly these three

  --lemma-in=<file>       : Read additional lemmas from <file>
  --lemma-out=<file>      : Log learnt lemmas to <file>
  --lemma-out-lbd=<n>     : Only log lemmas with lbd <= <n>

First call of clasp I used --lemma-out=file1.cnf --lemmaout-lbd=3
I suppose lbd is the length of the lemmas/clauses in the lemma-file?
But even when giving a length of 3 I see a lot clauses with a big length e.g. 992 or 10 or others.

Can I use multiple lemma in files?

e.g.

clasp ... --lemma-out=file1.cnf ...my_problem.cnf
clasp ... --lemma-in=file1.cnf --lemma-out=file2.cnf ...my_problem.cnf
clasp ... --lemma-in=file1.cnf --lemma-in=file2.cnf --lemma-out=file3.cnf ...my_problem.cnf

I am working with a timeout, e.g. do a new call every hour.
In reality I merge all file*.cnf to one file, reverse sort and make each line unique,
I see e.g. lines
1 0 0 0 1 85569
multiple times in a lemma file. I think this is due to multithreading, more than one thread finds same clause. Or bug?
Best regards,
Martin

**Comment by rkaminsk** [comment]
The LDB does not measure the length of a clause but the Literal Block Distance. Have a look at the paper "Predicting Learnt Clauses Quality in Modern SAT Solver".

You cannot pass the `--lemma-in` option multiple times.

In practice it can happen that a solver finds a clause multiple times. Every SAT solver implements some kind of clause deletion strategy. If a clause is deleted, it can be found again later.
