### ISSUE TITLE
Broken PDF URL at README.md

### ISSUE THREAD

**Issue by bcribas** [potassco/clasp#27]
Hi,

I found that the links to PDF files hosted at http://www.cs.uni-potsdam.de/ are broken.

Maybe these files should be hosted within the git project?

Thanks in advance,
-- Bruno Ribas

**Comment by BenKaufmann** [comment]
Hi Bruno,

thanks for the info. The issue was already addressed in PR https://github.com/potassco/clasp/pull/22 and is fixed in the dev branch. The master branch currently always reflects the state of the last release.
