### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rkaminsk** [potassco/clasp#28]
I was noticing today that GitHub properly detects the license for most of our projects except clasp. The reason might be because the `LICENSE` file does not start with the line `The MIT License`. Should we change this? I can do this if you give the okay.

**Comment by BenKaufmann** [comment]
Sure, go ahead.

**Comment by rkaminsk** [comment]
Done. Let's see if it makes a difference.

**Comment by rkaminsk** [comment]
Yes, now it is detected properly. ;)
