### ISSUE TITLE
Winner in stats

### ISSUE THREAD

**Issue by rkaminsk** [potassco/clasp#39]
For some reason clasp always reports the last thread as winner (with the attached example
[test.sm.gz](https://github.com/potassco/clasp/files/2718991/test.sm.gz)). With this example it is typically thread 0 which finds the model.

`````
clasp -t6 test.sm
...
Models       : 1+
Calls        : 1
Time         : 18.680s (Solving: 18.47s 1st Model: 18.46s Unsat: 0.00s)
CPU Time     : 110.905s
Threads      : 6        (Winner: 6)
`````

**Comment by BenKaufmann** [comment]
Thanks. This is indeed a regression in clasp-3.3.x. Fixed in dev.
