### ISSUE TITLE
Unclear clasp option

### ISSUE THREAD

**Issue by broesdecat** [potassco/clasp#4]
Hi,

For projective solution enumeration, the clasp --help states:
"--project[=\<arg\>]       : Enable projective solution enumeration"
What is the meaning of \<arg\> here? Intuitively, I would not expect the projective option to be parametrized?

Thx!
Broes

**Comment by BenKaufmann** [comment]
With \<arg\> one can control the two refinements we mentioned in Section 4 of our projective enumeration paper [1]. That is,
  - 1: variant d[]
  - 2: variant d[h]
  - 4: variant d[p]
  - 6: variant d[hp] (this is the default if \<arg\> is not given).

However, given that these refinements are rather specific, they are intentionally undocumented.

[1] http://www.cs.uni-potsdam.de/wv/pdfformat/gekasc09a.pdf

**Comment by broesdecat** [comment]
Then maybe also undocument the <arg> part in help? It was quite confusing as it seemed mandatory. A cursory read through section 4 did not bring a lot of additional understanding, so I will just leave it at the default :)

Thanks for the clarification!
Broes
