### ISSUE TITLE
Use the Clingo --time-limit option only on Solving phase

### ISSUE THREAD

**Issue by mircoianese** [potassco/clasp#47]
Hello,
I'm trying to run some benchmarks and I noticed that the `--time-limit` option also count the pre-processing and grounding phases so, with big amount of data, it kills the process even before it start the solving phase.

This is my current batch file:
```
for f in $FILES
do
	echo $f
	clingo 0 --time-limit=300 --mode=clingo -t 8 test.lp $f > ./benchmarks/clingo/results/result_$i.txt
	i=$((++i))
done
```

Is there any way to start the timer when the solving stage is reached?

Thank you!

**Comment by rkaminsk** [comment]
There is no such option. You could ground your program first and then solve it:

```
clingo --mode=gringo test.lp > test.asp
clingo --mode=clasp test.asp --time-limit=300
```

**Comment by ZombieTheBest** [comment]
> There is no such option. You could ground your program first and then solve it:
> 
> ```
> clingo --mode=gringo test.lp > test.asp
> clingo --mode=clasp test.asp --time-limit=300
> ```

That was exactly what I was looking for!
Thanks a lot!!

**Comment by mircoianese** [comment]
Sorry, I still have an issue: 

Running `clingo --mode=clasp 0 test.asp --time-limit=20 -t8` kills the process in "Reading from test.asp". So, still before starting the Solving step, right?

Any way to avoid this?
Thanks again!

**Comment by rkaminsk** [comment]
Yes, there is still reading and preprocessing. There is no option to just set a time limit on the solving time. When we do benchmarking we typically include these times.

**Comment by mircoianese** [comment]
Thanks!
