### ISSUE TITLE
Unclear exit code

### ISSUE THREAD

**Issue by cbettinger** [potassco/clasp#5]
Running clasp (3.2.1) with the attached DIMACS-CNF ([clasp-30.txt](https://github.com/potassco/clasp/files/796195/clasp-30.txt)) results in exit code 30.

The output says the formula is satisfiable so I would expect exit code 10.

Indeed the enum ExitCode in clasp_app.h does not list a exit code 30.

Could you please help me to understand this situation?

**Comment by BenKaufmann** [comment]
Exit code 30 is the logical "ORing" of exit codes 10 (a model was found) and 20 (the search-space was completely examined). Typically, this exit code is only relevant for optimization (an optimal model was found) or enumeration (all models were found). In your example, clasp found the satisfying assignment 
without doing a single choice and hence knows that it is the only one.
In the texp output, this is indicated by the missing "+" after the number of models in the 
"c Models" line.
