### ISSUE TITLE
Force CLASP to use preset configurations through libclasp's API

### ISSUE THREAD

**Issue by TheRealNebus** [potassco/clasp#6]
Hello,

I am using the ClaspFacade API in order to do Pseudo-Boolean optimization. However, I am not getting the same performance from CLASP using the API that I get when passing an .opb file to the CLASP application.
I believe it is due to the fact that I am not passing the default PB configuration (trendy) to the ClaspFacade when calling startPB.
This is the code that I have right now:

```
...
ClaspFacade clasp;
ClaspConfig clasp_config;
config.solve.optMode = MinimizeMode_t::optimize;
clasp.startPB(config);
...
```

Is there some way for me to obtain the trendy configuration (or others like crafty) as a ClaspConfig object and pass it to the ClaspFacade on the call to startPB? I have been looking through the code searching for a way to do so, but with no luck.

Thank you in advance.

Best regards,
Miguel Neves

**Comment by BenKaufmann** [comment]
Hi, 
the easiest thing would be to use Clasp::Cli::ClaspCliConfig instead of ClaspConfig.
For this, you have to
 - include <clasp/cli/clasp_options.h>
 - link against the libprogram_opts library

You can then do something like this:
```
Clasp::Cli::ClaspCliConfig config;
const char* args = "--config=trendy";
// init configuration to 'trendy'
config.setConfig(&args, &args + 1, Clasp::Problem_t::Pb);
...
```

**Comment by TheRealNebus** [comment]
Just tried it and it is working properly now. Thank you very much!

Best regards,
Miguel Neves
