### ISSUE TITLE
cmake can't find potassco

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [potassco/clasp#76]
I'm packaging clasp for gentoo overlay guru and it can't find `potassco` through cmake
```
CMake Error at CMakeLists.txt:101 (find_package):
  Could not find a package configuration file provided by "potassco"                                                                                                                                               (requested version 1.0) with any of the following names:

    potasscoConfig.cmake
    potassco-config.cmake

  Add the installation prefix of "potassco" to CMAKE_PREFIX_PATH or set
  "potassco_DIR" to a directory containing one of the above files.  If
  "potassco" provides a separate development package or SDK, be sure it has
  been installed.
```

The `potassco` cmake files are here

```
/usr/lib64/cmake/Potassco/PotasscoConfig.cmake
/usr/lib64/cmake/Potassco/PotasscoConfigVersion.cmake
/usr/lib64/cmake/Potassco/PotasscoTargets-relwithdebinfo.cmake
```

maybe `potassco` should be capitalized?

**Comment by rkaminsk** [comment]
Yes, the spelling is the issue. Note that the install target to install the development libraries is not tested at all. We do not use them here. At the moment, libpotassco, clasp, and clingo releases go hand in hand. Our binary packages bundle all of them and offer no way to install the systems separately. In case you are planning to release clingo, you will find that it uses parts of clasp that are not installed via its install target.

**Comment by BenKaufmann** [comment]
Addressed by @rkaminsk  in https://github.com/potassco/clasp/pull/77
Thanks :+1:
