### ISSUE TITLE
Question on ASP heuristic solution

### ISSUE THREAD

**Issue by Ckins** [potassco/clasp#8]
Hi, Ben.

After reading your paper - Conflict-Driven Answer Set Solving:From Theory to Practice, I feel such heuristics is really state-of-the-art.  As for further optimization on ASP, did you ever think of utilizing some **sufficient conditions for ASP** ? 

For example, Fages showed that a **call-consistent** normal logic program always has an answer set in 1994 and give a polynomial algorithm to construct an answer set. Later Bonatti extended the result in 2002 in his paper "Reasoning with infinite stable models II: Disjunctive programs". 

Actually, based on clasp, I have a toy implementation of the algorithm mentioned above. In my repo, clasp_plus. However, after experiments, I find only few problems contain such structures. In other words, those sufficient conditions **seem useless**. 

When I happen to notice that the developers of clasp are also on Git hub, I can't help leaving a comment here to ask **how you think of those sufficient conditions.**

Bests,
Kinsang

**Comment by BenKaufmann** [comment]
Hi Kinsang,

in clasp, we only use structural conditions like "tightness" and "head-cycle-freeness". 
You might want to look into work around the [DFLAT system](https://dbai.tuwien.ac.at/proj/dflat/), which uses particular results from parameterized complexity for decomposed ASP solving.

Best regards,
Ben

PS: I vaguely remember call-consistency but I'm actually not familiar with the result regarding the polynomial construction of an answer set. Can you give me a pointer on this?

**Comment by Ckins** [comment]
Hi Ben,

The polynomial construction are related to a few publications.
- Papadimitrious C H, Yannakakis M. Tie-breaking semantics and structural totality. 1997
- Fages F. Consistency of Clark's completion and existence of stable models. 1994

Ususally, only positive edges are taking into consideration in an atom dependency graph. The definitin of negative edge is similar to that of postive edge, but it links negative literals in the body with the head.

Call-consistency means: there is no cycle containing an odd numberof negative edges.

Let's make an example satisfying this condition:

a :-  not b.
b :- not a.

The atom dependency graph contains a cycle with two negative edges. The number is even, so this is a call-consistent program. According to the properties of call-consistency condition, it must have an answer set. 

The detail of construction is somewhat complex, if you are interested in it, I could post more information here. 

PS, about half year ago, I sent you some emails for details in clasp.  Your reply really helped me a lot. I am a senior student and my graduation design is about structural conditions in answer set solvers. For the spirit of open source, I am glad to contribute a little bit.

Best,
Kin

**Comment by BenKaufmann** [comment]
Thank you for the pointers!
