### ISSUE TITLE
Clasp binaries for Windows

### ISSUE THREAD

**Issue by a1880** [potassco/clasp#83]
Clingo no longer does offer precompiled Clasp binaries for Windows.

Is there some download repository to avoid the build process?

**Comment by rkaminsk** [comment]
We do not provide standalone binaries anymore. For Windows there are packages for conda. A clasp executable is part of the clingo package:

- https://anaconda.org/potassco/clingo
- https://anaconda.org/conda-forge/clingo

**Comment by a1880** [comment]
Thank you!

I could easily extract the clasp.exe from the clingo conda package.
Clasp is still a very fast SAT solver on par with recent releases of Armin Biere (CaDiCal, Kissat, Gimsatul).
