### ISSUE TITLE
Parse error in line 1:1: '%': unrecognized input format

### ISSUE THREAD

**Issue by artemsokhin-a4bee** [potassco/clasp#92]
**Prerequisites**:

System: 22.04 Ubuntu x86_64

**Description**:

Having an issue with clasp, built using the following commands

```bash
cmake -H. -Btest
sudo cmake --build test --target install
```

When I try executing clasp with the command
```bash
./clasp file.asp
```

it fails with an error
```
*** ERROR: (clasp): parse error in line 1:1: '%': unrecognized input format
```

If I remove parts with "%" it still fails with the same error, pointing to the first symbol in the file.
E.g. if the file is:
```
innocent(Suspect) :- motive(Suspect), not guilty(Suspect).
```
The execution fails with

```
*** ERROR: (clasp): parse error in line 1:1: 'i': unrecognized input format
```

Tried executing with `cat` and pipe - still got the same error.

**Comment by rkaminsk** [comment]
It looks like you want to use clingo and not clasp: 
- https://github.com/potassco/clingo
- https://potassco.org/clingo/run/

**Comment by artemsokhin-a4bee** [comment]
> It looks like you want to use clingo and not clasp:
> 
> * https://github.com/potassco/clingo
> * https://potassco.org/clingo/run/

Thanks, clingo worked for me
